##
# ZikulaBootstrapTheme variables
##
home:
  default_value: 3col_w_centerblock_home
  type: choice
  options:
    choices:
      1col: One column
      2col: Two columns
      2col_w_centerblock: Two columns with centerblock
      3col: Three columns
      3col_w_centerblock: Three columns with centerblock
      3col_w_centerblock_home: Three columns with centerblock home
master:
  default_value: 2col
  type: choice
  options:
    choices:
      1col: One column
      2col: Two columns
      2col_w_centerblock: Two columns with centerblock
      3col: Three columns
      3col_w_centerblock: Three columns with centerblock
      3col_w_centerblock_home: Three columns with centerblock home
admin:
  default_value: 1col
  type: choice
  options:
    choices:
      1col: One column
      2col: Two columns
      2col_w_centerblock: Two columns with centerblock
      3col: Three columns
      3col_w_centerblock: Three columns with centerblock
      3col_w_centerblock_home: Three columns with centerblock home
